In [3]:
import numpy as np
# create array using numpy
#create a 1D array


arr1= np.array([1,2,3,4,5])
print(arr1)

print(type(arr1))
print(arr1.shape)




[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


## 2-D array

In [4]:
arr2= np.array([1,2,3,4,5])
arr2.reshape((1,5)) #1 row 5 colmuns

array([[1, 2, 3, 4, 5]])

In [5]:
arr3=np.array([[1,2,3,4,5],[6,7,8,9 ,10]])
print(arr3)
print(type(arr3))

print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Attributes of numpy

In [9]:
arr= np.array([[1,2,3],[6,7,8,]])


print("Array:",arr)
print("Shape: ",arr.shape)
print("Number of Dimensions: ",arr.ndim)
print("Size (number of elements): ",arr.size)
print("Data Type: ",arr.dtype)
print("Item Size (in bytes): ",arr.itemsize)


Array: [[1 2 3]
 [6 7 8]]
Shape:  (2, 3)
Number of Dimensions:  2
Size (number of elements):  6
Data Type:  int64
Item Size (in bytes):  8


In [10]:
### Numby Vactorized operations
arr1= np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Elements Wise addition
print("Addition: ", arr1+arr2)

### Elements Wise subtraction    
print("Subtraction: ", arr1-arr2)

### Elements Wise multiplication   
print("Multiplication: ", arr1*arr2)
### Elements Wise divison   
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [12]:
# Universal Functions
arr=np.array([2,3,4,5,6])
#Square root
print("Square Root: ",np.sqrt(arr))
# Exponentioanl
print("Exponentioanl: ",np.exp(arr))
# sin@
print("Sin@: ", np.sin(arr))
#Natural log
print("Natural Log:",np.log(arr))

Square Root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponentioanl:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin@:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
# Array Slicing and indexing
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Arry : \n,",arr)


Arry : 
, [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(arr[0][0])
print(arr[1:,2:])
print(arr[0:2][1:])
print(arr[1:,1:3])

1
[[ 7  8]
 [11 12]]
[[5 6 7 8]]
[[ 6  7]
 [10 11]]


In [30]:
#Modify the arry elements
arr[0,0]=100
print(arr)

arr[1:]=100
print(arr)


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
# Statistical Concepts- Normalization
# to having mean of 0 and standard deviation of 1
data= np.array([1,2,3,4,5])
# Calculate mean and std deviation  
mean= np.mean(data)
std= np.std(data)

# Normalization
normalized_data=(data - mean)/ std
print("Normalized Data: ",normalized_data)

print(np.mean(normalized_data))
print(np.std(normalized_data))

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [35]:
# Statistical Concepts- Mean,Median,Standard Deviation,Variance
data = np.array([1,2,3,4,5,6,7,8,9,10])
# Mean 
mean= np.mean(data)
print("Mean: ", mean)
# Median
median=np.median(data)
print("Median: ", median)
# Standard Deviation 
std= np.std(data)
print("Standard Deviation: ", std)
# Veriance
var= np.var(data)
print("Variance: ",var)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [50]:
# Loginal Operations
data= np.array([1,2,3,4,5,6,7,8,9,10])
print(data[(data>=5) & (data <= 8)])

[5 6 7 8]
